sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# TODO: document what all the above commands do

language: node_js
node_js: 10.13.0
cache: npm # don't reinstall packages from scratch every time
script: npm run ci
